name: Run Spring Boot Tests with Testcontainers (Maven)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Verify Docker is available
        run: docker --version

      - name: Run tests with Maven
        run: mvn clean verify
